import type { schema } from "@/db";

type Track = typeof schema.tracks.$inferInsert;
type Lesson = typeof schema.lessons.$inferInsert;

export const tracks: Track[] = [
  { id: "pyramid-principle", title: "Pyramid Principle", description: "Lead with the answer and structure the support.", competency: "storyboarding", order: 1 },
  { id: "hypothesis-driven", title: "Hypothesis-Driven Problem Solving", description: "Issue trees, hypotheses and the analyses that prove them.", competency: "problem_solving", order: 2 },
  { id: "action-titles", title: "Action Titles and Exhibits", description: "Titles that tell the story; charts that prove them.", competency: "output_quality", order: 3 },
  { id: "handling-pushback", title: "Handling Pushback", description: "Acknowledge, explore, reframe.", competency: "difficult_conversations", order: 4 },
  { id: "delivering-bad-news", title: "Delivering Bad News", description: "Say the hard thing early, clearly and kindly.", competency: "difficult_conversations", order: 5 },
  { id: "managing-scope", title: "Managing Scope", description: "Options, not refusals.", competency: "client_management", order: 6 },
  { id: "running-a-steerco", title: "Running a SteerCo", description: "Honest status and decisions, not just nods.", competency: "client_management", order: 7 },
  { id: "executive-presence", title: "Executive Presence", description: "Brevity, calm and command of the room.", competency: "client_management", order: 8 },
  // ---------- Client leadership & business development (Manager → Director) ----------
  { id: "account-leadership", title: "Account Leadership", description: "Own the relationship, map the buying centre and grow the account on merit.", competency: "client_management", order: 9 },
  { id: "winning-work", title: "Winning Work", description: "Qualify hard, shape the need and write proposals that answer the client's question.", competency: "client_management", order: 10 },
  { id: "commercial-conversations", title: "Commercial Conversations", description: "Price on value, defend the fee and trade, never just concede.", competency: "client_management", order: 11 },
  { id: "engagement-setup", title: "Setting Up an Engagement", description: "Take an engagement from signed proposal to a staffed, governed team, and close it cleanly.", competency: "client_management", order: 13 },
  { id: "trusted-advisor", title: "Trusted Advisor", description: "Earn the next conversation with C-suite clients through insight, not activity.", competency: "client_management", order: 12 },
];


export const lessons: Lesson[] = [
  {
    id: "pyramid-answer-first",
    trackId: "pyramid-principle",
    title: "Answer first",
    level: "analyst",
    durationMin: 6,
    order: 1,
    practiceScenarioId: "meridian-data-platform",
    blocks: [
      { type: "text", markdown: "Senior readers want the answer before the reasoning. The pyramid starts with a **governing thought** — the single sentence you want them to remember — then groups the support beneath it." },
      { type: "key_idea", markdown: "If your reader stopped after the first sentence, would they know what you recommend and why?" },
      {
        type: "example_pair",
        bad: "We reviewed the data platform's spend, architecture, data quality and adoption over the last three years.",
        good: "The £14m platform works; value is blocked by poor claims and customer data with no business owners. Fund five owned use cases and fix data at source.",
        annotation: "The first describes the work. The second gives the answer and the action.",
      },
      {
        type: "quiz",
        question: "Which is the best governing thought for a board paper on the data platform?",
        options: [
          "Overview of the data platform programme",
          "Only 3 of 20 use cases are live",
          "The platform isn't the problem: unowned, poor-quality data is. Refocus funding on five owned use cases",
          "We should review the data strategy",
        ],
        answerIndex: 2,
        explanation: "It answers 'why' and 'so what' in one sentence, and tells the board what to do.",
      },
    ],
  },
  {
    id: "pyramid-mece",
    trackId: "pyramid-principle",
    title: "MECE key lines",
    level: "consultant",
    durationMin: 8,
    order: 2,
    practiceScenarioId: "calder-managed-services",
    blocks: [
      { type: "text", markdown: "Key lines under the governing thought should be **mutually exclusive** (no overlap) and **collectively exhaustive** (nothing important missing). Group by a single logic: steps, options, or causes." },
      { type: "key_idea", markdown: "Three to four key lines. If you have seven, you haven't synthesised yet." },
      {
        type: "quiz",
        question: "Which set of key lines is MECE for 'should we renew, re-tender or insource IT services?'",
        options: [
          "Cost; Re-tender; Risk",
          "Renew costs most and fixes nothing; re-tender is cheapest and lowest risk; insourcing saves less and is hard to staff",
          "Service levels; Benchmarks; HR view; Everything else",
        ],
        answerIndex: 1,
        explanation: "One line per option, each with its verdict — no overlap and nothing missing. The first mixes a criterion with an option.",
      },
    ],
  },
  {
    id: "hypothesis-tree",
    trackId: "hypothesis-driven",
    title: "Start with a hypothesis tree",
    level: "consultant",
    durationMin: 7,
    order: 1,
    practiceScenarioId: "meridian-data-platform",
    blocks: [
      { type: "text", markdown: "Don't boil the ocean. Write down your best guess at the answer, break it into the **conditions that must be true**, and only collect data that proves or disproves each one." },
      {
        type: "example_pair",
        bad: "Workstreams: architecture review, tool assessment, data quality, stakeholder interviews, benchmarking.",
        good: "Hypothesis: value is blocked by data, not technology. True if (1) blocked use cases trace to poor data, (2) the poor data has no business owner, (3) the platform performs where data is good.",
        annotation: "The second tells the team exactly what to test — and when to stop.",
      },
      { type: "key_idea", markdown: "A good hypothesis can be proved wrong in a week. If it can't, it's a topic, not a hypothesis." },
      {
        type: "quiz",
        question: "Which of these is a testable hypothesis for why a CRM programme is late?",
        options: [
          "We should review the CRM programme",
          "The delay is driven by data migration: two of three mock loads failed and the fix needs client data owners we don't have",
          "There are many factors affecting delivery",
        ],
        answerIndex: 1,
        explanation: "It names a cause and the evidence that would prove or disprove it within a week.",
      },
    ],
  },
  {
    id: "titles-carry-the-number",
    trackId: "action-titles",
    title: "Titles that carry the number",
    level: "analyst",
    durationMin: 5,
    order: 1,
    practiceScenarioId: "calder-managed-services",
    blocks: [
      { type: "text", markdown: "An action title states the insight the exhibit proves — usually with the number that matters. Keep it to **15 words or fewer**." },
      {
        type: "example_pair",
        bad: "Five-year cost comparison of sourcing options",
        good: "Re-tendering saves £8.1m over five years against renewing as-is",
        annotation: "The topic tells the reader what the chart is about. The action title tells them what to conclude.",
      },
      {
        type: "quiz",
        question: "Which is the best action title for a chart of service desk performance against target?",
        options: [
          "Service desk performance, last 12 months",
          "First-time fix is 62% against a 70% target, driving a third of repeat calls",
          "Service desk KPIs and trends",
        ],
        answerIndex: 1,
        explanation: "It states the insight and the number, so a reader gets the point from the title alone.",
      },
    ],
  },
  {
    id: "pushback-acknowledge",
    trackId: "handling-pushback",
    title: "Acknowledge before you argue",
    level: "consultant",
    durationMin: 5,
    order: 1,
    practiceScenarioId: "operating-model-leak",
    blocks: [
      { type: "text", markdown: "When a client pushes back emotionally, facts land badly until the emotion is acknowledged. Use **acknowledge → explore → reframe**." },
      {
        type: "example_pair",
        bad: "I understand, but the design is based on benchmarks from twelve comparable housing associations.",
        good: "You're right — you should have heard this from us, not a screenshot, and I'm sorry. Can we go through what the draft gets wrong for your teams and tenants?",
        annotation: "'I understand, but' cancels the acknowledgement. Own it, then ask.",
      },
      {
        type: "quiz",
        question: "What should come first when a client is angry about how they found out about a change?",
        options: ["The evidence for the change", "An acknowledgement of how they found out", "An escalation to your partner"],
        answerIndex: 1,
        explanation: "Trust first, then content.",
      },
    ],
  },
  {
    id: "bad-news-early",
    trackId: "delivering-bad-news",
    title: "Bad news early, with a path",
    level: "consultant",
    durationMin: 6,
    order: 1,
    practiceScenarioId: "genai-pilot-not-ready",
    blocks: [
      { type: "text", markdown: "Lead with the headline, give the two or three facts behind it, then the **path forward**. Bad news with no path feels like a dead end; bad news with a path feels like leadership." },
      {
        type: "example_pair",
        bad: "There are a few things to work through on the pilot before we think about scaling, mainly around accuracy and some risk items.",
        good: "It isn't ready to scale yet: accuracy is 81% against a 90% target and the DPIA isn't signed. We can be ready in eight weeks — here's the plan and what you can tell the board now.",
        annotation: "The first hedges. The second is clear, specific and gives her something to say.",
      },
      {
        type: "quiz",
        question: "You've found the programme will miss its go-live by six weeks. When should the sponsor hear?",
        options: [
          "At the next monthly SteerCo, with the full analysis",
          "Today, in a short conversation with the headline, the cause and the recovery options",
          "Once you've confirmed a recovery plan, so you don't alarm them",
        ],
        answerIndex: 1,
        explanation: "Early news with options lets the sponsor act. Late news, however polished, removes their choices.",
      },
    ],
  },
  {
    id: "scope-options",
    trackId: "managing-scope",
    title: "Offer options, not refusals",
    level: "consultant",
    durationMin: 5,
    order: 1,
    practiceScenarioId: "scope-creep-crm",
    blocks: [
      { type: "text", markdown: "A flat 'no' damages the relationship; a silent 'yes' damages the delivery. Make the trade-off explicit and offer choices: **swap**, **phase 2**, or **change request**." },
      { type: "key_idea", markdown: "\"Happy to — if we add the chatbot now, the CRM release slips by three sprints. Would you rather swap it for the reporting pack, or scope it as phase 2?\"" },
      {
        type: "example_pair",
        bad: "Sorry, that's out of scope.",
        good: "Happy to look at the chatbot. Adding it now pushes the CRM release back three sprints. Would you rather swap it for the reporting pack, run it as phase 2, or raise a change request so we can staff it?",
        annotation: "The first ends the conversation. The second keeps the relationship and makes the trade-off the client's decision.",
      },
      {
        type: "quiz",
        question: "A client asks for a new dashboard 'while you're here'. What's the best first response?",
        options: [
          "Agree, to keep the client happy",
          "Refuse: it isn't in the statement of work",
          "Acknowledge it, explain the impact on the current plan, and offer to swap, phase or change-request it",
        ],
        answerIndex: 2,
        explanation: "Options turn a scope fight into a decision the client owns.",
      },
    ],
  },
  {
    id: "honest-rag",
    trackId: "running-a-steerco",
    title: "Report the real RAG",
    level: "manager",
    durationMin: 6,
    order: 1,
    practiceScenarioId: "watermelon-status",
    blocks: [
      { type: "text", markdown: "A 'watermelon' programme is green on the outside and red inside. Reporting Amber when the facts say Red buys a fortnight and costs your credibility. Pair a Red status with a **recovery plan and the decision you need**: date, scope or resource." },
      {
        type: "quiz",
        question: "Mock data load 2 failed and testing is at 38% against a 70% plan, 11 weeks from go-live. What should the SteerCo see?",
        options: [
          "Amber, with a note that the team is confident of recovery",
          "Red, with a recovery plan and a decision on date, scope or resource",
          "Green until the next mock load, to avoid alarm",
        ],
        answerIndex: 1,
        explanation: "The facts say Red. The SteerCo's job is to make the decision that recovers it — give them that decision.",
      },
      {
        type: "example_pair",
        bad: "Status: Amber. The team is working hard on data migration and remains confident.",
        good: "Status: Red. Mock load 2 failed and testing is at 38% against a 70% plan. To protect the date we need a decision today: add four data engineers for six weeks, or move go-live by a month.",
        annotation: "The second gives the facts and the decision the SteerCo has to make.",
      },
    ],
  },
  {
    id: "ten-minutes-with-the-ceo",
    trackId: "executive-presence",
    title: "Ten minutes with the CEO",
    level: "manager",
    durationMin: 5,
    order: 1,
    practiceScenarioId: "ten-minute-ceo",
    blocks: [
      { type: "text", markdown: "Executives decide on **outcome, cost, risk and timing** — not architecture. Open with the decision you need, then the one number and the one risk that matter." },
      {
        type: "example_pair",
        bad: "We assessed three architecture options against fourteen criteria including interoperability, scalability and vendor roadmap.",
        good: "I'm asking you to take a phased SaaS move to the board next month: £18m over five years, about £5m a year back from 2028, and it removes the outage risk the CQC asked about.",
        annotation: "Methodology can wait for the appendix.",
      },
      {
        type: "quiz",
        question: "You have ten minutes with the Chief Executive. What should your first sentence be?",
        options: [
          "A summary of the work you've done so far",
          "The decision you need from them, with the cost and the benefit",
          "An overview of the three options you considered",
        ],
        answerIndex: 1,
        explanation: "Executives listen for the ask. Start there; the detail can follow if they want it.",
      },
    ],
  },
  // ---------- Account leadership ----------
  {
    id: "map-the-buying-centre",
    trackId: "account-leadership",
    title: "Map the buying centre",
    level: "manager",
    durationMin: 7,
    order: 1,
    practiceScenarioId: "extend-the-engagement",
    blocks: [
      { type: "text", markdown: "Technology and transformation work is rarely bought by one person. Before you sell anything, map the **buying centre**: who signs, who influences, who blocks and who uses what you deliver. Most lost follow-ons were lost to someone the team never met." },
      { type: "key_idea", markdown: "For each stakeholder, know three things: **what they're measured on**, **what they think of us**, and **who on our side owns the relationship**. A blank in any column is a risk." },
      {
        type: "example_pair",
        bad: "Our sponsor is the CIO and she's very happy, so the phase 2 extension should be straightforward.",
        good: "The CIO sponsors us, but the CFO signs anything over £500k and Procurement wants a competitive tender. Our partner meets the CFO next week; I'll take the Head of Procurement through our value evidence before then.",
        annotation: "One happy sponsor isn't an account plan. The second names the signer, the blocker and who covers each.",
      },
      {
        type: "quiz",
        question: "Your sponsor loves the work, but the follow-on needs CFO approval and you've never met the CFO. What's the best next step?",
        options: [
          "Ask the sponsor to forward the proposal to the CFO",
          "Ask the sponsor for an introduction and prepare a CFO-level view of value delivered so far",
          "Wait for the CFO to ask for a meeting",
        ],
        answerIndex: 1,
        explanation: "Get in front of the signer with what they care about (value in £, risk), and let your sponsor be your champion rather than your courier.",
      },
    ],
  },
  {
    id: "delivery-to-account-plan",
    trackId: "account-leadership",
    title: "From delivery to account plan",
    level: "director",
    durationMin: 8,
    order: 2,
    practiceScenarioId: "extend-the-engagement",
    blocks: [
      { type: "text", markdown: "The best source of new work is the work you're doing now. A one-page **account plan** turns delivery insight into growth: the client's top three priorities, where we've proven value, the gaps we've seen, the relationships we need, and the next two conversations to have." },
      { type: "key_idea", markdown: "Sell the **next problem**, not the next phase. 'Phase 2' sounds like more of the same; 'the data ownership gap that's blocking £4m of value' sounds like a reason to act." },
      {
        type: "example_pair",
        bad: "We'd love to discuss extending the team into phase 2 — we've built a great relationship and know the systems well.",
        good: "Three of your five use cases are blocked by claims data with no owner. We've seen it first-hand. A six-week data ownership sprint would unblock about £4m a year — shall I set out how?",
        annotation: "The first is about us. The second is about their problem, uses evidence only the delivery team has, and asks a small question.",
      },
      {
        type: "quiz",
        question: "Which is the strongest basis for proposing follow-on work?",
        options: [
          "The team is already on site, so it's cheaper to continue",
          "A specific problem we've seen in delivery, quantified, linked to a priority the client has",
          "Our firm's wider capabilities in the area",
        ],
        answerIndex: 1,
        explanation: "Continuity is a nice-to-have. A quantified problem tied to their priorities is a reason to buy.",
      },
    ],
  },
  // ---------- Winning work ----------
  {
    id: "qualify-before-you-chase",
    trackId: "winning-work",
    title: "Qualify before you chase",
    level: "manager",
    durationMin: 6,
    order: 1,
    practiceScenarioId: "first-meeting-cio",
    blocks: [
      { type: "text", markdown: "Bids are expensive, and losing one you should never have chased costs more than the bid. Qualify every opportunity on four questions: **Is there a real, funded need? Can we win? Can we deliver? Is it worth winning?** If you can't answer 'yes' with evidence, find out or walk away." },
      { type: "key_idea", markdown: "\"Can we win?\" is mostly about **who we know and what they think of us** before the tender lands. If the first you heard of it was the RFP, someone else probably shaped it." },
      {
        type: "quiz",
        question: "An RFP for a £2m ERP assessment arrives unexpectedly from a council you've never worked with. The deadline is in 10 days. What's the most important question?",
        options: [
          "Do we have ERP credentials?",
          "Who shaped this requirement, and do we have any relationship with the buyer?",
          "Can we price below the budget?",
        ],
        answerIndex: 1,
        explanation: "An unexpected RFP is often written around a competitor. Without a relationship or insight into the real need, your win probability is low however strong the credentials.",
      },
    ],
  },
  {
    id: "discovery-not-pitch",
    trackId: "winning-work",
    title: "Discovery, not pitch",
    level: "manager",
    durationMin: 7,
    order: 2,
    practiceScenarioId: "first-meeting-cio",
    blocks: [
      { type: "text", markdown: "In a first meeting, the person asking the best questions wins, not the one with the best slides. Spend at least two-thirds of the time on the client: their situation, what's at stake, what they've tried, and how they'll decide." },
      { type: "key_idea", markdown: "Use **situation → impact → implication** questions. 'What happens if the migration slips past March?' teaches you more, and makes the need more urgent to them, than any capability slide." },
      {
        type: "example_pair",
        bad: "Let me walk you through our cloud migration methodology and some recent case studies.",
        good: "Before I say anything about us — you mentioned the board is nervous about the data-centre exit. What's driving the March date, and what happens if it slips?",
        annotation: "The first pitches before understanding. The second earns the right to propose by finding what's at stake.",
      },
      {
        type: "quiz",
        question: "Thirty minutes into a first meeting, how much should you have spent talking about your firm?",
        options: [
          "Most of it: they need to know what you do",
          "Very little: the time should go on their situation, what's at stake and how they'll decide",
          "Exactly half",
        ],
        answerIndex: 1,
        explanation: "Clients buy from people who understand their problem. Capability slides can wait for the second meeting.",
      },
    ],
  },
  {
    id: "proposals-answer-the-question",
    trackId: "winning-work",
    title: "Proposals that answer the question",
    level: "director",
    durationMin: 8,
    order: 3,
    practiceScenarioId: null,
    blocks: [
      { type: "text", markdown: "Most proposals open with the firm, the methodology and the team. The client reads the first page and the price. Put **your understanding of their problem, the outcome you'll deliver and why you** on page one, in their words." },
      { type: "key_idea", markdown: "Write the executive summary as a pyramid: the outcome you'll deliver, then three reasons to choose you that a competitor couldn't credibly claim." },
      {
        type: "example_pair",
        bad: "Founded in 1998, our firm is a leading provider of digital transformation services with over 2,000 consultants worldwide.",
        good: "You need the new CRM live before renewal season without losing the 14% of members who renew by phone. We'll get you there in 20 weeks, with a phone-first migration we've run for two other UK mutuals.",
        annotation: "The client should recognise their own problem in your first sentence.",
      },
      {
        type: "quiz",
        question: "What should the first page of a proposal do?",
        options: [
          "Introduce the firm and its credentials",
          "Restate the client's problem and the outcome, and say why you're best placed",
          "Set out the detailed workplan",
        ],
        answerIndex: 1,
        explanation: "Credentials and workplans support the answer; they aren't the answer.",
      },
    ],
  },
  // ---------- Commercial conversations ----------
  {
    id: "defend-value-not-rate",
    trackId: "commercial-conversations",
    title: "Defend value, not the rate",
    level: "director",
    durationMin: 7,
    order: 1,
    practiceScenarioId: "fee-pushback",
    blocks: [
      { type: "text", markdown: "When a client says 'you're too expensive', they usually mean 'I can't yet justify this to someone else'. Don't defend your day rate; **reconnect the fee to the outcome** and help them make the case internally." },
      { type: "key_idea", markdown: "Never give something for nothing. If you move on price, **trade**: scope, timing, payment terms, a reference or a commitment to phase 2." },
      {
        type: "example_pair",
        bad: "I understand. We could probably bring the fee down by 15% if that helps.",
        good: "I understand the budget pressure. The £640k gets you live before the contract renewal, which avoids the £1.1m extension. If we need to reduce the fee, we could phase the data migration into Q3. What matters most to you: the date or the full scope?",
        annotation: "The first concedes instantly and signals the price was padded. The second ties the fee to value and offers a trade.",
      },
      {
        type: "quiz",
        question: "Procurement asks for a 20% discount 'as standard'. What's the best response?",
        options: [
          "Agree to 10% as a compromise",
          "Ask what's driving it, restate the value, and offer options that change scope or terms rather than the rate",
          "Refuse any discussion of price",
        ],
        answerIndex: 1,
        explanation: "Explore first, then trade. An unexplained discount teaches the client your prices are negotiable by default.",
      },
    ],
  },
  {
    id: "price-the-outcome",
    trackId: "commercial-conversations",
    title: "Price the outcome, share the risk",
    level: "director",
    durationMin: 6,
    order: 2,
    practiceScenarioId: "fee-pushback",
    blocks: [
      { type: "text", markdown: "Time-and-materials is easy to buy and easy to cut. For work with a measurable outcome, consider **fixed price for defined scope** or a **gain-share** element. It shows confidence and moves the conversation from cost to value — but only take risk you can control." },
      { type: "key_idea", markdown: "Before offering a risk-share, check three things: can the outcome be measured, can we influence it, and is the baseline agreed in writing?" },
      {
        type: "example_pair",
        bad: "We'll do it on time and materials at our standard rates — that's simplest for everyone.",
        good: "We'll fix the fee at £420k for the defined scope, with £60k at risk against the agreed reduction in repeat visits, measured from the March baseline.",
        annotation: "The second shows confidence and ties your fee to the outcome the client cares about, on terms you can measure and influence.",
      },
      {
        type: "quiz",
        question: "When is a gain-share arrangement a bad idea?",
        options: [
          "When the outcome is easy to measure",
          "When the result depends mostly on things your firm can't influence, or there's no agreed baseline",
          "When the client is keen on it",
        ],
        answerIndex: 1,
        explanation: "Only share risk you can see, measure and influence.",
      },
    ],
  },
  // ---------- Trusted advisor ----------
  {
    id: "earn-the-next-conversation",
    trackId: "trusted-advisor",
    title: "Earn the next conversation",
    level: "director",
    durationMin: 7,
    order: 1,
    practiceScenarioId: "first-meeting-cio",
    blocks: [
      { type: "text", markdown: "C-suite clients take meetings that make them smarter. Bring a **point of view**: one insight about their business, sector or peers that they didn't have. Then leave a reason to meet again, not a brochure." },
      { type: "key_idea", markdown: "Trust = (credibility + reliability + intimacy) ÷ self-orientation. The fastest way to lose trust is to make the meeting about your sale." },
      {
        type: "example_pair",
        bad: "Thanks for your time. I'll send over our capability deck and some case studies.",
        good: "Three of the building societies we work with have cut cloud run costs by a fifth by sorting rightsizing before the data-centre exit. I'll send you the one-page comparison, and could we pick up the board question in a fortnight?",
        annotation: "Insight, a specific follow-up and a reason to meet again.",
      },
      {
        type: "quiz",
        question: "What's the best way to end a first meeting with a CIO?",
        options: [
          "Promise to send your capability deck",
          "Offer a specific, useful follow-up linked to what they told you, and suggest a date to discuss it",
          "Ask when their next procurement round starts",
        ],
        answerIndex: 1,
        explanation: "A useful follow-up earns the next meeting; a brochure rarely does.",
      },
    ],
  },
  {
    id: "say-no-to-grow",
    trackId: "trusted-advisor",
    title: "Say no to grow",
    level: "director",
    durationMin: 5,
    order: 2,
    practiceScenarioId: null,
    blocks: [
      { type: "text", markdown: "Recommending against work your firm could sell is the most powerful trust-building move you have. Clients remember the adviser who said 'you don't need us for that'." },
      {
        type: "quiz",
        question: "A client asks you to run a large AI strategy programme, but their data isn't ready and a smaller fix would deliver more. What builds the most long-term value?",
        options: [
          "Sell the programme — they asked for it",
          "Recommend the smaller data fix first, and say why the strategy work should wait",
          "Propose both together to maximise the fee",
        ],
        answerIndex: 1,
        explanation: "You lose some fee today and earn the next five conversations.",
      },
    ],
  },
  {
    id: "engagement-scope-and-success",
    trackId: "engagement-setup",
    title: "Lock the scope and what success means",
    level: "manager",
    durationMin: 8,
    order: 1,
    practiceScenarioId: "start-on-monday",
    blocks: [
      { type: "text", markdown: "Before anyone is staffed, turn the proposal into a **statement of work (SOW)** that both sides sign. It sets out the objectives, what's in and out of scope, the deliverables and their acceptance criteria, assumptions, client dependencies, timeline, fees and change control. Most disputes later trace back to something that was 'understood' but never written down." },
      { type: "key_idea", markdown: "Write acceptance criteria the client could check without you in the room. \"Board-ready business case, signed off by the CFO\" beats \"business case\"." },
      {
        type: "example_pair",
        bad: "Scope: support the client with their ERP selection.",
        good: "Scope: shortlist two ERP vendors against 40 agreed requirements and deliver a board-ready recommendation by 14 March. Out of scope: implementation planning and data migration. The client provides process owners for six workshops and access to current system data by week 2.",
        annotation: "The second sets boundaries, dependencies and a finish line both sides can check.",
      },
      {
        type: "quiz",
        question: "Which item is most often missing from SOWs that end in disputes?",
        options: [
          "The firm's credentials",
          "Client dependencies and assumptions, and what happens if they slip",
          "The team's CVs",
        ],
        answerIndex: 1,
        explanation: "If the client is late with data or people, you need the agreed consequence in writing before it happens.",
      },
    ],
  },
  {
    id: "staff-the-team-and-associates",
    trackId: "engagement-setup",
    title: "Staff the team, including associates",
    level: "manager",
    durationMin: 9,
    order: 2,
    practiceScenarioId: null,
    blocks: [
      { type: "text", markdown: "Start from the **roles the work needs**, not the people who are free. For each role, write a short spec: the outcome it owns, skills, seniority, whether it's client-facing, days a week, and start and end dates. Fill roles from your own bench first. Bring in **associates** (independent consultants) where you need specialist skills, extra capacity or sector credibility the client will recognise." },
      { type: "key_idea", markdown: "Select associates on **evidence of delivery**, not the CV. Ask for a recent, comparable piece of work, take two references from people who managed them, and run a short scenario interview: \"The client's data is late in week 2. What do you do?\"" },
      {
        type: "example_pair",
        bad: "Sarah's free from Monday and has done some data work, so let's put her on the data strategy role.",
        good: "The data lead must run workshops with the CDO and own the target architecture. Nobody on the bench has done that in insurance, so we'll interview two associates with Lloyd's market data experience and take references from their last engagement leads.",
        annotation: "Role first, evidence second, availability last.",
      },
      {
        type: "quiz",
        question: "An associate has an excellent CV and can start tomorrow, but can't give a reference from a recent engagement lead. What's the right call?",
        options: [
          "Book them: the CV speaks for itself",
          "Hold off until you've seen comparable work or a reference, and line up an alternative",
          "Book them on a lower day rate to offset the risk",
        ],
        answerIndex: 1,
        explanation: "Associates represent your firm to the client from day one. Evidence of delivery matters more than speed.",
      },
    ],
  },
  {
    id: "onboard-associates-properly",
    trackId: "engagement-setup",
    title: "Contract and onboard associates properly",
    level: "manager",
    durationMin: 8,
    order: 3,
    practiceScenarioId: "start-on-monday",
    blocks: [
      { type: "text", markdown: "Before an associate starts, close the paperwork that protects the client, the associate and your firm:\n\n- a contract with a notice period and IP ownership\n- confidentiality and conflict-of-interest declarations\n- the off-payroll working (IR35) status determination\n- professional indemnity insurance\n- data protection terms if they'll handle personal data\n- any client vetting, such as BPSS for UK government work\n\nThen brief them as you would an employee: your methods, your quality bar, how to represent the firm, and who reviews their work before the client sees it." },
      { type: "key_idea", markdown: "Agree who makes the **off-payroll (IR35) status determination**, and record it, before day one. It depends on how the work is contracted and on the size of the end client, so take advice rather than assume." },
      {
        type: "example_pair",
        bad: "The associate starts Monday. We'll sort out the contract and security checks once they're in.",
        good: "Contract signed, with a four-week notice period and IP assigned to us. Conflict declaration returned. Status determination issued and recorded. BPSS check submitted two weeks before the start date. The engagement manager reviews their first deliverable before it goes to the client.",
        annotation: "Starting before vetting and a signed contract can breach the client's terms and leaves your firm exposed if anything goes wrong.",
      },
      {
        type: "quiz",
        question: "For a UK central government client, which check usually has to be complete before an associate can access client systems?",
        options: [
          "A LinkedIn recommendation",
          "The Baseline Personnel Security Standard (BPSS) check",
          "A Companies House search",
        ],
        answerIndex: 1,
        explanation: "BPSS is the standard pre-employment screening for government work. Build its lead time into your mobilisation plan.",
      },
    ],
  },
  {
    id: "governance-and-kick-off",
    trackId: "engagement-setup",
    title: "Set up governance and run the kick-off",
    level: "manager",
    durationMin: 8,
    order: 4,
    practiceScenarioId: "start-on-monday",
    blocks: [
      { type: "text", markdown: "In the first two weeks, set up the machinery that keeps the engagement on track: a sponsor and a SteerCo that meets on a fixed cadence, a RACI for decisions, a **RAID log** (risks, assumptions, issues and dependencies), a weekly status report with an honest RAG, and a communications plan. Then run a kick-off that aligns everyone on the outcome, roles and the first four weeks." },
      { type: "key_idea", markdown: "A good kick-off ends with three things agreed: what success looks like, who decides what, and what happens in the first fortnight." },
      {
        type: "example_pair",
        bad: "Kick-off agenda: introductions, our methodology, our team's experience, questions.",
        good: "Kick-off agenda: the outcome and how we'll measure it; the decisions we need from you and when; roles and RACI; the first four weeks, week by week; the risks we already see; how we'll report progress (weekly status, monthly SteerCo).",
        annotation: "The client should leave knowing what they owe you and what they'll get.",
      },
      {
        type: "quiz",
        question: "Two weeks in, the client's data extract is late and will push the timeline. What should you do first?",
        options: [
          "Keep it to yourself until you know whether it matters",
          "Log it in the RAID log as an issue against the client dependency, and raise it with its impact at the next weekly status",
          "Absorb it by working extra hours",
        ],
        answerIndex: 1,
        explanation: "Logging it against the agreed dependency protects the timeline and the fee, and gives the sponsor the chance to fix it.",
      },
    ],
  },
  {
    id: "commercials-and-margin",
    trackId: "engagement-setup",
    title: "Plan resourcing, commercials and margin",
    level: "director",
    durationMin: 8,
    order: 5,
    practiceScenarioId: null,
    blocks: [
      { type: "text", markdown: "Before you mobilise, build the resourcing plan and check the engagement makes money: days by role by week, cost rates (including associate day rates), fees, contingency and the billing schedule. Margin is usually lost in the first month, through over-staffing, or in the last, through unbilled extras." },
      { type: "key_idea", markdown: "Know three numbers before kick-off: the planned margin, the contingency you're holding, and the date of the first invoice." },
      {
        type: "example_pair",
        bad: "We'll staff it fully from week one to show commitment, and work out the numbers at month end.",
        good: "Two people for the three-week discovery, rising to five for the build. The associate data lead costs £850 a day against a £1,300 charge-out rate. The engagement director holds 8% contingency. The first invoice goes out on discovery sign-off in week 3.",
        annotation: "The second ties staffing to the work, and protects both margin and cash.",
      },
      {
        type: "quiz",
        question: "Associate costs are running 15% over plan in week 5. What's the first move?",
        options: [
          "Quietly cut the associate's days and hope quality holds",
          "Re-forecast to completion, find the cause (scope, rework or planning) and agree a fix: a change request, re-phasing or using contingency",
          "Ask the client for more money without explaining why",
        ],
        answerIndex: 1,
        explanation: "Re-forecast first, then fix the cause. A change request only works if the scope really changed.",
      },
    ],
  },
  {
    id: "close-and-hand-over",
    trackId: "engagement-setup",
    title: "Close the engagement and hand over",
    level: "manager",
    durationMin: 6,
    order: 6,
    practiceScenarioId: null,
    blocks: [
      { type: "text", markdown: "How an engagement ends is what the client remembers. Plan the close from the start: formal acceptance of deliverables, a handover pack and knowledge transfer to the client's team, roll-off for associates (client data and equipment returned, access removed), a lessons-learned review, the final invoice, and a request for a reference or case study." },
      { type: "key_idea", markdown: "Get **written acceptance** against the SOW criteria before the team rolls off. It's much harder to get once they've gone." },
      {
        type: "example_pair",
        bad: "Last day is Friday. We'll email the final deck and send the invoice.",
        good: "Acceptance signed against the six SOW criteria; two handover sessions with the client's PMO; associate access removed and the return of client data confirmed; lessons-learned session booked; final invoice issued with the acceptance note; reference requested from the sponsor.",
        annotation: "The second closes every loop: the contract, the client's team, security, learning, cash and the next sale.",
      },
      {
        type: "quiz",
        question: "Which roll-off step most protects your firm when associates leave the engagement?",
        options: [
          "A farewell lunch",
          "Removing their system access and confirming client data has been returned or deleted",
          "Sending them a feedback survey",
        ],
        answerIndex: 1,
        explanation: "Access and data left behind are a security and contractual risk for the client, and for you.",
      },
    ],
  },
];
